# Generated by Django 3.2.13 on 2024-02-13 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Istochnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rudnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type_rabot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DvishenieMTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateTimeField(auto_now_add=True)),
                ('my_date', models.DateField()),
                ('enc', models.CharField(max_length=50)),
                ('type_dvisheniya', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('itog_count', models.IntegerField()),
                ('sdo', models.CharField(max_length=100)),
                ('nomer_incidenta', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('istochnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.istochnik')),
                ('rudnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.sklad')),
                ('type_rabot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.type_rabot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
