# Generated by Django 3.2.13 on 2024-02-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rudnik',
        ),
    ]
