# Generated by Django 3.2.13 on 2024-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0003_auto_20240217_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='itog_count',
            field=models.IntegerField(null=True),
        ),
    ]
