# Generated by Django 3.2.13 on 2024-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0004_alter_dvisheniemtr_itog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='itog_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
