# Generated by Django 3.2.13 on 2024-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0006_alter_dvisheniemtr_itog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='type_dvisheniya',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход'), ('Выдан', 'Выдан'), ('Списан', 'Списан')], max_length=50, verbose_name='Тип движения'),
        ),
    ]
