# Generated by Django 3.2.13 on 2024-02-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0008_spravochnikoborudovaniya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='enc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.spravochnikoborudovaniya'),
        ),
    ]
