# Generated by Django 3.2.13 on 2024-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0011_alter_dvisheniemtr_enc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
