# Generated by Django 3.2.13 on 2024-02-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0012_alter_dvisheniemtr_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='itog_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вычисляемое количество'),
        ),
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='type_rabot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.type_rabot', verbose_name='Тип работ'),
        ),
    ]
