# Generated by Django 3.2.13 on 2024-02-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_uchastok', '0013_auto_20240227_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='my_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='real_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Реальная дата'),
        ),
    ]
