# Generated by Django 3.2.13 on 2024-02-27 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad_uchastok', '0014_auto_20240227_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='enc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.spravochnikoborudovaniya', verbose_name='ЕНС'),
        ),
        migrations.AlterField(
            model_name='dvisheniemtr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
