# Generated by Django 5.0.2 on 2024-04-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sklad_uchastok', '0023_alter_dvisheniemtr_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_dogovora', models.CharField(max_length=255)),
                ('kratkoe_opisanie', models.CharField(max_length=255)),
                ('date_formir_proekta', models.DateField(auto_now_add=True, null=True, verbose_name='Дата формирования проекта')),
                ('date_podpis_proekta', models.DateField(blank=True, null=True, verbose_name='Дата подписания проекта')),
                ('valyta', models.CharField(blank=True, choices=[('долларах', 'долларах'), ('евро', 'евро'), ('рублях', 'рублях'), ('фунтах-стерлингах', 'фунтах-стерлинга')], max_length=30, null=True, verbose_name='Валюта')),
                ('nds', models.CharField(blank=True, choices=[('0', '0'), ('20%', '20%')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postavshik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status_narydZakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPostavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypePostupleniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Naryd_zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_Zakaz_naryd', models.CharField(max_length=255, unique=True, verbose_name='№ заказ-наряда')),
                ('nomer_document', models.CharField(max_length=255, unique=True, verbose_name='№ документа')),
                ('date_sozdaniya', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_otpravki', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('date_podpisaniy', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('date_zakritiy', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('nomer_dogovora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.dogovor', verbose_name='№ Договора')),
                ('postavshik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.postavshik', verbose_name='Постовщик')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.status_narydzakaz', verbose_name='Статус')),
                ('status_postavki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.statuspostavki', verbose_name='Статус поставки')),
                ('type_postupleniya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.typepostupleniya', verbose_name='Тип поступления')),
            ],
        ),
        migrations.AddField(
            model_name='dogovor',
            name='kontragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.postavshik', verbose_name='Контрагент'),
        ),
        migrations.CreateModel(
            name='DvishenieSkladMagaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(verbose_name='Дата')),
                ('date_vipuska', models.CharField(max_length=100, verbose_name='Дата выпуска')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('type_dvisheniya', models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход'), ('Выдан', 'Выдан')], max_length=50, verbose_name='Тип движения')),
                ('itog_count', models.IntegerField(blank=True, null=True, verbose_name='Вычисляемое количество')),
                ('nomer_vhod_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Входящего документа')),
                ('date_vhod_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Входящего документа')),
                ('price_za_edinicy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('enc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.spravochnikoborudovaniya', verbose_name='ЕНС')),
                ('nomer_dogovora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad_centeralniy.dogovor', verbose_name='Договор')),
                ('peredano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_uchastok.sklad', verbose_name='Рудник/Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('nomer_zakaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_centeralniy.naryd_zakaz', verbose_name='№ заказа')),
                ('type_postupleniya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklad_centeralniy.typepostupleniya', verbose_name='Тип постулпения')),
            ],
        ),
    ]
