# Generated by Django 5.0.2 on 2024-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0003_alter_dvishenieskladmagaz_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvishenieskladmagaz',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='dvishenieskladmagaz',
            name='price_za_edinicy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за ед.'),
        ),
    ]
