# Generated by Django 5.0.2 on 2024-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0004_alter_dvishenieskladmagaz_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvishenieskladmagaz',
            name='price_za_edinicy',
            field=models.FloatField(default=0, verbose_name='Цена за ед.'),
        ),
    ]
