# Generated by Django 5.0.2 on 2024-06-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0005_alter_dvishenieskladmagaz_price_za_edinicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvishenieskladmagaz',
            name='date_vhod_document',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Входящего документа'),
        ),
        migrations.AlterField(
            model_name='dvishenieskladmagaz',
            name='nomer_vhod_document',
            field=models.CharField(max_length=255, verbose_name='№ Входящего документа'),
        ),
    ]
