# Generated by Django 5.0.2 on 2024-07-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0009_alter_dvishenieskladmagaz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvishenieskladmagaz',
            options={'permissions': (('can_view_dvishCS', 'fsdaf'), ('can_delete_dvishCS', 'saf'), ('can_edit_dvishCS', 'fdsfasf'), ('can_list_dvishCS', 'fdsfasfasdff'))},
        ),
    ]
