# Generated by Django 5.0.2 on 2024-07-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0010_alter_dvishenieskladmagaz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvishenieskladmagaz',
            options={},
        ),
    ]
