# Generated by Django 5.0.2 on 2024-07-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_centeralniy', '0011_alter_dvishenieskladmagaz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvishenieskladmagaz',
            options={'permissions': [('can_view_DvishenieSkladMagaz', 'Can view DvishenieSkladMagaz'), ('can_edit_DvishenieSkladMagaz', 'Can edit DvishenieSkladMagaz'), ('can_delete_DvishenieSkladMagaz', 'Can delete DvishenieSkladMagaz')]},
        ),
    ]
