# Generated by Django 3.2.13 on 2024-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sklad',
            field=models.CharField(default='0000', max_length=30),
        ),
    ]
