# Generated by Django 3.2.13 on 2023-12-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_date_hired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['-id']},
        ),
    ]
